version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint*'
      vitest:
        patterns:
          - '@vitest/*'
          - 'vitest'
