version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      minor-and-patch:
        update-types:
          - 'patch'
          - 'minor'
      eslint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint*'
